version: '3'

services:
  db:
    build:
      context: "./db"
    tty: true
    restart: always
    container_name: gauth_db
    volumes:
      - "./db/_data:/data/db"
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    #networks:
    #  - gauth_network
  mongo-express:
    #build:
    #  context: "./db"
    image: mongo-express
    tty: true
    restart: always
    container_name: mongo-express
    volumes:
      - "./db/_data:/data/db"
    ports:
      - "7999:8081"
    environment:
      # ME_CONFIG_MONGODB_PORT: 27018
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://root:root@db:27018/
    #networks:
    #  - gauth_network
    depends_on:
      - db
    healthcheck:
      test: wget --quiet --tries=3 --spider http://admin:admin@10.10.10.60:8081 || exit 1
      interval: 30s
      retries: 3
      start_period: 20s
      timeout: 10s
  app:
    build:
      context: "./app"
    tty: true
    restart: always
    container_name: gauth_app      
    volumes:
      - "./app:/app"
    ports:
      - "8800:8080"
    #networks:
    #  - gauth_network
    depends_on:
      - db